### ISSUE TITLE
Profiilisivu

### ISSUE THREAD

**Issue by latolli** [MuistotKartalla/muistot-frontend#43]
Nykyisellään sivulla ei ole profiilisivua (ainakaan minä en löytänyt), vaan ainoastaan sivut, joista voi vaihtaa käyttäjän tietoja tai käyttäjänimeä. Voisi olla järkevämpää poistaa nämä sivut valikosta ja tehdä tilalle yksi uusi profiilisivu, josta käyttäjä näkisi selkeästi omat tiedot. Ja tältä sivulta pääsisi myös vaihtamaan tietoja / käyttäjänimeä.
![profile_idea](https://user-images.githubusercontent.com/55877751/198540220-e09ac4d8-6610-4fd0-8df2-556870a672eb.png)

**Comment by latolli** [comment]
Mitäs @ttokola olisi tästä ideasta mieltä?

**Comment by ttokola** [comment]
Vaikuttaa hyvin perustellulta ja selkeältä parannukselta 👍🏻
