### ISSUE TITLE
Käyttäjänimen editointi-ikoni: ei ymmärrä

### ISSUE THREAD

**Issue by ttokola** [MuistotKartalla/muistot-frontend#55]
![image](https://user-images.githubusercontent.com/1726098/203987459-adff2488-cde7-4200-b94f-741844f2835c.png)

Käyttäjänimen editointi-ikoni ei ole ymmärrettävä: ikonin pitäisi olla pienempi, ja heti käyttäjänimen perässä, jotta käyttäjä ymmärtää, että siitä muokataan käyttäjänimeä. Menin mobiilinäkymään, ja luulin että siitä muokataan kaikkia tietoja.

**Comment by ttokola** [comment]
Periaatteessa voisi olla käyttäjänimen jälkeen vain tekstilinkkikin tyyliin: "(vaihda)"

**Comment by latolli** [comment]
Korjattu lisäämällä nappi käyttäjänimen vaihdolle:
![image](https://user-images.githubusercontent.com/55877751/205617192-948bf117-2935-4227-87b0-216b8fd9c5a9.png)
